name: Continuous Persistent VPS
 
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:
Expand
message.txt
3 KB
Download and login 
https://tailscale.com/                                                                                                                                                                                                                                                                                                                                   sudo su  |      apt update && upgrade -y    |   apt  install bash     |   apt install curl 
<                                                                                                                            Panel                                                                                                                                       >
[OWNER] RasINGamerZ
[VPS]
 — 8/11/2025 5:30 PM
bash <(curl -s https://pterodactyl-installer.se)
<                                                                                                                            Theme                                                                                                                                    >
cd /var/www/pterodactyl

php artisan down
----------------------------------
curl -L https://github.com/Nookure/NookTheme/releases/latest/download/panel.tar.gz | tar -xzv
----------------------------------------------------------------------
chmod -R 755 storage/* bootstrap/cache
---------------------------------------------------------------
composer install --no-dev --optimize-autoloader
---------------------------------------------------
php artisan view:clear
php artisan config:clear
---------------------------------------------------------------
php artisan migrate --seed --force
-----------------------------------------------
chown -R www-data:www-data /var/www/pterodactyl/*
----------------------------------------------
php artisan queue:restart
-------------------------------------
php artisan up
------------------
https://github.com/
[OWNER] RasINGamerZ
[VPS]
 — 8/12/2025 4:29 PM
@everyone @here @Member 
﻿
name: Continuous Persistent VPS
 
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:
 
jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # Just under 6 hours
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Set hostname to biralo
        run: sudo hostnamectl set-hostname biralo
 
      - name: Download VPS backup (if any)
        uses: actions/download-artifact@v4
        with:
          name: vps-backup
          path: ./backup
        continue-on-error: true
 
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y tmate curl unzip sudo net-tools neofetch
 
      - name: Install Tailscale official script
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
 
      - name: Restore backup files
        run: |
          if [ -f ./backup/backup.zip ]; then
            unzip -o ./backup/backup.zip -d /
          else
            echo "No backup found, starting fresh"
          fi
 
      - name: Restore Tailscale state
        run: |
          if [ -f /opt/vps-backup/data/tailscaled.state ]; then
            sudo mkdir -p /var/lib/tailscale
            sudo cp /opt/vps-backup/data/tailscaled.state /var/lib/tailscale/tailscaled.state
            sudo chmod 600 /var/lib/tailscale/tailscaled.state
          fi
 
      - name: Start Tailscale
        run: |
          sudo tailscaled &
          sleep 8
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname=biralo || echo "Tailscale already up"
 
      - name: Create user biralo with sudo
        run: |
          if ! id -u biralo >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash biralo
            echo "biralo:biralo" | sudo chpasswd
            sudo usermod -aG sudo biralo
            echo "biralo ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/biralo
          fi
 
      - name: Start tmate session for SSH access
        uses: mxschmitt/action-tmate@v3
 
      - name: Show Tailscale IP and tmate info
        run: |
          echo "🔗 Tailscale IP:"
          tailscale ip -4 || echo "Tailscale IP not found"
          echo ""
          echo "🔑 tmate SSH session:"
          cat $HOME/.tmate.sock/ssh
 
      - name: Sleep to keep VPS alive
        run: sleep 21600  # 6 hours
 
      - name: Backup VPS data and tailscale state
        run: |
          sudo mkdir -p /opt/vps-backup/data
          sudo cp /var/lib/tailscale/tailscaled.state /opt/vps-backup/data/
          sudo chown -R $USER:$USER /opt/vps-backup
          zip -r backup.zip /opt/vps-backup
 
      - name: Upload VPS backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: vps-backup
          path: backup.zip
